# Generated by Django 5.0.4 on 2024-04-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='null', null=True, upload_to=''),
        ),
    ]
